import GlassCard from "@/components/GlassCard";
import SectionHeading from "@/components/SectionHeading";

type CaseStudy = {
  tag: string;
  title: string;
  description: string;
  result: string;
};

const CASE_STUDIES: CaseStudy[] = [
  {
    tag: "Fintech",
    title: "Real-time fraud detection for a mid-market bank",
    description:
      "A regional bank was drowning in false-positive fraud alerts generated by a decade-old rules engine, forcing analysts to chase noise instead of real threats. We replaced it with an ML pipeline that scores every transaction in under 80 milliseconds, learning from historical fraud patterns instead of static thresholds.",
    result: "47% reduction in false-positive fraud flags",
  },
  {
    tag: "Healthcare",
    title: "Clinical documentation copilot for a hospital network",
    description:
      "Clinicians across a multi-site hospital network were spending hours after each shift finishing patient notes. We built an LLM assistant that listens to ambient visit audio and drafts structured clinical documentation, with every note routed through a clinician review step before it enters the chart.",
    result: "6 minutes saved per patient visit",
  },
  {
    tag: "Retail",
    title: "Demand forecasting for a national retailer",
    description:
      "Disconnected forecasting spreadsheets left store teams guessing at replenishment, leading to chronic stockouts on high-velocity SKUs. We unified point-of-sale, weather, and promotional calendar data into a single forecasting model that feeds store-level ordering decisions.",
    result: "18% reduction in stockouts",
  },
];

export default function CaseStudiesPage() {
  return (
    <div className="mx-auto max-w-7xl px-6 py-24 sm:py-32">
      <SectionHeading
        eyebrow="Case Studies"
        title="Results, not slideware"
        description="Three engagements where we shipped production AI systems and moved the metrics that mattered to the business."
      />

      <div className="mt-16 grid grid-cols-1 gap-8 lg:grid-cols-3">
        {CASE_STUDIES.map((study) => (
          <GlassCard key={study.title} className="flex flex-col">
            <span className="mb-4 inline-block w-fit rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-medium uppercase tracking-widest text-cyan-300">
              {study.tag}
            </span>
            <h3 className="text-xl font-semibold tracking-tight text-white">
              {study.title}
            </h3>
            <p className="mt-4 flex-1 text-sm leading-relaxed text-gray-400">
              {study.description}
            </p>
            <p className="mt-6 border-t border-white/10 pt-4 text-lg font-semibold text-white">
              {study.result}
            </p>
          </GlassCard>
        ))}
      </div>
    </div>
  );
}
